@node Environment Utilities
@section Environment Utilities

These are forms for manipulating the current processes working
environment. Note that these are only valid in single-threaded
excecuting, and attempting to use them in multi-threaded environments
may lead to undefined behaviour (in accordance with the underlying C
functions).

Provided by the module @code{(hnh util env)}.

@defmac let-env bindings body ...
Similar to @var{let}, but sets environment variables for the code in
body. Restores the old values once we leave.

A variable can also be removed from the environment, by setting its
value to @code{#f}.
@end defmac


@defmac with-working-directory directory thunk
Run @var{thunk} with the working directory set to @var{directory}.

Note that this probably isn't thread safe. See source for more
inforamtion.
@end defmac


@defmac with-locale1 category locale thunk
Run @var{thunk} with the locale @var{category} temporarily set to
@var{locale}.
@end defmac
