@node Table
@section Table

An immutable table, where all operations on the table return a new
table with the wanted changes carried out. All keys @emph{must} be
symbols.

@defun table [named-type]
Constructs a new empty table. A named type can be given, in which case
all elements inserted into the table will be checked against the type.
@end defun

@defun table? x
Is @var{x} a table?
@end defun

@defun table-type table
Returns the named type for the table, or @code{#f}.
@end defun

@defmac table-of var type
Syntax for defining tables of a given type.

@example
(typecheck var (table-of string?))
@end example
@end defmac

@defun table-empty? table
Checks if the table is empty.
@end defun

@defun table-get table key [default=#f]
Retrive value form table, returns @var{default} if key isn't in the
table.
@end defun

@defun table-preview tree k
Return an optional with the value under @var{k}.
@end defun

@defun table-put table key value
Insert new value into table, overwriting anything previously stored
under that key. Returns a new table with the values set.
@end defun

@defun table-remove table key
Returns a new table with @var{key} removed.
@end defun

@deftp {Lens} table-focus key
Lens for focusing a given field of the table. If the value exists,
then @code{(just <value>)} is passed to the continuation, and
@code{(nothing)} otherwise. If the value returned is
@code{(just <value>)} then the value is set to that, while a return
value of @code{(nothing)} removes the key from the table.
@end deftp

@defun table->list table [proc=cons]
Return the list gained by applying @var{proc} to each key-value pair
in the table.

The keys will be sorted. TODO will they?
@end defun

@defun alist->table alist
Construct a new table from the given alist.
@end defun

@defun table-equal? a b [comperator=equal?]
Checks if @var{a} and @var{b} have the same key set, and that for each
key the element in @var{a} and @var{b} are equal, in regards to @var{comperator}.
@end defun

@defun table-diff a b [#:compare=equal?] [#:report=built-in-report]
@anchor{table-diff}
Checks what's different between the two tables. It returns a list of
forms, where each form is the result of calling the @var{report}
procedure on the key, which has type
@code{symbol, (optional (table-type a)), (optional (table-type b)) -> any}.
In the cases that the value is equal in both tables, or absent from
both tables, the @var{report} procedure will not be called.

The default report procedure returns the following variants:
@itemize @bullet{}
@item @code{`(,key _ ,(serialize b)}
@item @code{`(,key ,(serialize a) _)}
@item @code{`(,key ,(serialize a) ,(serialize b))}
@end itemize

The order each diff form is returned is unspecified.

@var{compare} must be a procedure taking two values, the one from the
left and right table in the case of a key conflict, and which must
return a boolean (equivalent) stating if the values are equal. Note
that weak equality (for example, sets containing the same elements in
different orders, or strings being case insensitively equal) are very
valid equivalance procedures here.

Not to be confuseod with @ref{table-difference}.
@end defun

@defun table-pop table key
Returns 2 values:
@itemize @bullet
@item @code{just} the value focused by key if present, and
@code{nothing} otherwise
@item the table without the specified key
@end itemize
@end defun

@defun table-any table
Like table pop, but returns an arbitrary value. Useful if the tree
needs to be destructured in some way where the actual contents doesn't matter.

Returns either just a value, or nothing.
@end defun

@defun table-filter-map f table
Apply @var{f} to each key and value in the table. @var{f} must must
return an optional value, where just the value means to keep the node,
while nothing means to remove the node.
@end defun

@defun table-union tables ...
Returns a new table whose keys are the union of all the keys in all
the given tables. If a key is present in multiple tables, then the
last one ``wins''.
@end defun

@defun table-intersection tables ...
Return a new table where the keys are the intersection of the keys of
all the given tables. If a key is present in multiple tables, then the
first encountered one wins.
@end defun

@defun table-difference a b
@anchor{table-difference}
Returns a new table of all the keys present in @var{a} but not in @var{b}.

Not to be confused with @ref{table-diff}.
@end defun
