@node Table
@section Table

An immutable table, where all operations on the table return a new
table with the wanted changes carried out. All keys @emph{must} be
symbols.

@defun table
Constructs a new empty table.
@end defun

@defun table? x
Is @var{x} a table?
@end defun

@defun table-get table key [default=#f]
Retrive value form table, returns @var{default} if key isn't in the
table.
@end defun

@defun table-put table key value
Insert new value into table, overwriting anything previously stored
under that key. Returns a new table with the values set.
@end defun

@defun table-remove table key
Returns a new table with @var{key} removed.
@end defun

@deftp {Lens} table-focus key
Lens for focusing a given field of the table. If the value exists,
then @code{(just <value>)} is passed to the continuation, and
@code{(nothing)} otherwise. If the value returned is
@code{(just <value>)} then the value is set to that, while a return
value of @code{(nothing)} removes the key from the table.
@end deftp

@defun table->list table
Return an association list with the same content as the table.

The keys will be sorted.
@end defun

@defun alist->table alist
Construct a new table from the given alist.
@end defun
