@node Configuration
@section Configuration

At their core, configurable fields are simply Guile parameters, with
some documentation attached to them. At program startup, a
configuration file is loaded, which simply sets these parameters.

Configuration loading is done through the @code{(calp load-config)} module.

@defun load-config filename
Runs code in the given file.
@end defun

@defun find-config-file [alternative]
If @var{alternative} is given, attempt to load that file, and fail
otherwise.
If @var{alternative} isn't given, attempt to load one of the following
in order, and fail if none is found:
@itemize @bullet
@item @code{$XDG_CONFIG_HOME/calp/config.scm}
@item @code{$XDG_CONFIG_DIRS/calp/config.scm}
(note that config-dirs is a list)
@item @code{/etc/calp/config.scm}
@end itemize
@end defun

Declaration of configurable fields is done through the module
@code{(calp util config)}. Note however that since the configuration
file is simply a scheme script, it can set any field as it sees fit,
not just the explicitly configurable ones.

@defmac define-config name default parameters ...

    @deftp {Parameter} #:pre procedure
        Procedure called on the set configuration value before
        it is saved. This allows transformation of the value,
        and validation checking.

        If the procedure returns @code{#f}, then an error is signaled.
    @end deftp

    @deftp {Parameter} #:post procedure
        Procedure called on the (potentially converted by pre)
        configuration value. Intended to be used to update further fields.
    @end deftp

    @deftp {Parameter} #:description desc
        A plain-text description of the configurable field.

        This should be marked for translation. Note however that the
        define-syntax macro removes this text, and translation is
        completely handled by external tools.
    @end deftp

@end defmac

@defun {(ensure predicate)} value
Helper procedure for @code{pre} hooks. Curried function which checks
if @var{value} satisfies @var{predicate}, and if so returns @var{value}.

@example
(define-public ((ensure predicate) value)
  (if (predicate value)
      value #f))
@end example
@end defun

@defmac with-source proc
Ensures that a procedure gets it source captured. Recommended to be
used when a procedure is set as a configuration value, to allow
printing it later.

Note that the procedure body is embedded as is, meaning that module
resolution is left as an exercise to the reader.
@end defmac

@subsection Entry Point

@deftp {Entry Point} get-config
Searches the code base for configuration declarations, and prints them
all in a ini-like format.
@end deftp
