@node Optional Values
@section Optional Values

Provided by the module @code{(hnh util optional)}.

@defun just x
@defunx nothing
@end defun

@defun fromJust x
@end defun

@defun optional? x
@defunx just? x
@defunx nothing? x
@end defun

@defmac optional-of var type
Syntax for an optional which is only allowed to hold a specific
value. Note that nothings are untyped, so all nothings are the same.
@end defmac

@deftp {Lens} just*
Lens which focuses the value of @code{just} fields.
@end deftp

@defun unjust opt [dflt]
Return the value of the optional @var{opt}, or @var{dflt} if there is
nothing there.
@end defun

@subsection Destructuring Patterns
@deftp {Matcher} just x
@end deftp

@deftp {Matcher} nothing
@end deftp
