@node Exception & Warning Utilities
@section Exception & Warning Utilities
@anchor{warning}

Warnings are like exceptions, but only fatal when wanted.

@code{(hnh util exceptions)}

@defun warning fmt args ...
Emit a warning.

First, the procedure stored in @code{warning-handler} is called with
the format and arguments, and output set to the current error port.
If @code{warnings-are-errors} is true, then an exception of type
@code{warning} is thrown, the format string and argument list.

@var{fmt} must be a basic Guile format string. @var{args} is the
arguments to this format string.
@end defun

@deftp {parameter} warning-handler
A procedure which logs all warnings (irregardless of if warnings are
errors or not), in a way deemed fit by the user. The default handler
simply emits a message to the current error port.
@end deftp

@deftp {parameter} warnings-are-errors
Boolean parameter, which if set causes warnings to be thrown as exceptions.
@end deftp

@defun fatal fmt args ...
Display the message in fmt, populated with args, then raises the UNIX
signal SIGINT, which kills the program.
@end defun

@defun filter-stack pred? stack
@c TODO document me
@end defun


@defun unreachable procedure fmt args
Marks that a code path should be unreachable. Throws an exception
which should never be caught (an @code{(exit -1)} would also have
worked, but would make debugging harder).

@var{procedure} is the procedure which reached an ``impossible''
state, @var{fmt} a format string, and @var{args} arguments to that
format string.
@end defun
