@node dragable
@subsection dragable.js

@c TODO This text is just yanked from the old org file, along with the
@c source codes header. It should probably be rewritten.

Manually apply =bind_popup_control= to the statusbar of a floating
"window".  Nothing is required from the component, but the "window"
must have 'popup-container' ∈ =class=

@defun bind_popup_control nav
Apply to a given component to make it draggable.
Drag area (usually a title bar) should be be the only argument.
It is REQUIRED that the object which should be moved have the class
@code{popup-container}.

@example
<div class='popup-container'>
    ...
        <nav />
    ...
</div>
@end example
@end defun
