@node formatters
@subsection formatters

Formatting procedures used by some components.
@c TODO can we have a backref of every node containing @ref{formatters-proc}?

@deftypevar {Map<string, (e:HTMLElement, d:VEvent, s:any) => void>} formatters
@anchor{formatters-proc}

Each procedure takes three arguments. The HTML-element which contents
should be replaced, the VEvent containing all data, and the target
value, as returned by @ref{VEvent.getProperty}.
@end deftypevar

@deftypevr {Window Value} {Map<string, (e:HTMLElement, d:VEvent, s:string) => void>} formatters
Same object as @xref{formatters-proc}. Provided for @xref{user-additions.js}.
@end deftypevr
