
@node script
@subsection script.js

@dfn{Main} for my javascript, and also currently dumping ground for stuff.

@deftp {class} EventCreator

@defmethod EventCreator create_empty_event
@end defmethod

@defmethod EventCreator create_event_down intended_target
@end defmethod

@defmethod EventCreator create_event_move pos_in [round=1] [wide_element=false]
@end defmethod

@defmethod EventCreator create_event_finisher callback
@end defmethod

@end deftp

@defun place_in_edit_mode event
@end defun

@c window.onload is here in source file

@defun get_property event field default_value
Returns the @emph{value} slot of given field in @var{event}, creating it if needed.

@itemize
@item
@var{el}: the event to work on

@item
@var{field}: name of the field

@item
@var{default_value}: default value when creating

@item
@var{bind_to_ical} should this property be added to the icalendar subtree?
@end itemize
@end defun

@defun bind_properties el [wide_event=false]
@anchor{bind_properties}
@ref{binders}
  Properties are icalendar properties.

  p['name'] to get and set value (also updates any connected slots)

  p['_value_name'] for raw value
  p['_slot_name'] for connected slots, Vector of pairs, where the
                  car should be a reference to the slot, and the
                  cdr a procedure which takes a slot and a value
                  and binds the value to the slot.
@end defun


