@node VComponent Create
@section Vcomponent Create

Procedures for declarativly creating components (instead of the
primitive ``procedural'' API).

@defun create-vcomponent type [key: prop] ... [children]
Creates a new vcomponent of @var{type} (such as @code{VCALENDAR} or @code{VEVENT}.

After that follows a list of alternating keyword objects, and
values which will map to the property values. The keywords are
converted to symbols and up-cased. Each value is either an explicit
vline object, a @code{with-parameters} form, a ``raw'' Guile value, or
a list of the aforementioned.

The final argument may be a (non-keyworded) list of vcomponents, which
will become the created components children.

@example
(create-vcomponent 'VEVENT
  summary: "My event"
  dtstart: (with-parameters tzid: "Europe/Stockholm" (current-datetime))
  categories: (list "A" "B")
  (list (valarm)))
@end example
@end defun

@defun with-parameters [key: param] ... value
Allows setting parameters for a property in conjunction with @code{create-vcomponent}.

@var{value} follows the same rules as in @code{create-vcomponent}. Multiple
@var{key}, @var{value} pairs can be given, where each key must be a keyword.

Technically, this is just an alternative syntax for creating vlines.
@end defun

@defun vcalendar
@defunx vevent
@defunx vtodo
@defunx vjournal
@defunx vfreebusy
@defunx vtimezone
@defunx valarm
@defunx standard
@defunx daylight
Calls @code{create-vcomponent}, with type set to the procedure name (but
up-cased).
@end defun

