@node Data Formats
@section Data Formats

@c TODO update this documentation, making it clearer.
@c However, maybe wait until we rewrite the module structure to match
@c the media type paths.

Data formats are the serialization formats for components.
The primary serialization format is iCalendar, but xCalendar and
sxCalendar also exists.

Each available format should be included as
@code{(vcomponent formats @var{format-name})}.
Which module corresponds to what file type is currently defined out of
band.

@c TODO specify if `serializer` is required or optional

@defun calendar-data-format
@end defun

@defun calendar-data-format? x
@end defun

@defun parser
@end defun

@defun serializer
@end defun

@c TODO rename to text/icalendar
@subsection iCal
RFC 5545

@defvar format
@end defvar

@c TODO rename to application/calendar+xml
@subsection xCal
RFC 6321

@defvar format
@end defvar

@c TODO rename to application/calendar+json
@subsection jCal
RFC 7265

@defvar format
@end defvar
