@node Data Stores
@section Data Stores

Data stores are persistant stores for events, such as databases or the
file system. Data stores operate on the high level vcomponent objects
defined by this program, and how they are stored to an underlying
system is an implementation detail not handled by this API. Instead,
see each individual store for details, and how they may interface with
other programs.

Calendar objects in themself are immutable (TODO reference other part
of the documentation), calendar store handles the mutation required to
properly store objects somewhere. The expected usage pattern is to
``check out'' an object from a store (possibly locking it TODO if
looking existed), transform the object into a new calendar object
matching the wanted form, and handing it back to the store for storage.

Clients should not cache calendar objects retrieved from a store,
since another process may at any time modify the underlying data.

Currently, all data stores assume that all clients are very well
behaved, and never tries to put an invalid entry, put an existing
entry onto a new href, or any other funny stuff.

@deftp {GOOPS class} <calendar-data-store>
Base class for all stores. Contains no fields in itself, and shouldn't
be instanciated, but used to provide defaults for a number of the
below mentioned methods.
@end deftp

@defun calendar-data-store? x
@end defun

@defun store-uri->store uri
Given an URI object, attempt to construct the store it refers to.
This is mostly useful for command line usage.

Store URIs hase the scheme @code{store}, with the store implementation
embedded in the host component, the ``special'' parameter @var{path}
in the @code{path} component, and other parameters query encoded in
the URIs query.

The procedure @code{create-instance} is looked up in the module
@code{(vcomponent data-stores @var{host})}, which will be applied to
the query parameters as a list of alternating keywords and values.
The path component will always be included as @code{#:path @var{path}}.

The decision to ``require'' a path component is since most stores
actually have one, it makes for much cleaner URIs, and it only
slightly inconveniences stores which don't have the concept of a path.
@end defun

@defun create-instance #:path path [other keyword arguments ...]
Procedure with must me implemented by each data store. This is the
primary procedure for creating instances of each store, and is what is
used by @code{store-uri->store}. The @var{path} parameter must be
accepted, since it's an inherent part of an URI, it may however be
ignored if the concept of a path doesn't apply to the store.

See each individual stores documentation for applicable arguments.
@end defun

@deftp {GOOPS method} store-uri store
Return a URI object which can be passed to @code{store-uri->store} to
establish a new connection to the store.
@end deftp

@deftp {GOOPS method} close-store! store
Analogous to closing a file. Default implementation is a no-op.

Note that you probably want to @code{flush!} the store before closing it.

TODO shouldn't close-store! force a flush?
@end deftp

@subsection Writing Data

@deftp {GOOPS method} put-event! store href vcomponent
Create or update a given event in the store.

This method takes a VCALENDAR object, which must only contain a single
logical event (possibly as multile VEVENT object), and any
referenced VTIMEZONE objects.

TODO who updates DTSTAMP?
TODO who ensures component validity?

Note that this doesn't guarantee a writing to the disk, see
@code{flush!} for that.
@end deftp

@deftp {GOOPS method} remove-by-href! store href
Remove an entry from a store by its href. If href isn't present in the
store, then this operation @emph{must} be a noop.

TODO flushing?
@end deftp

@c TODO `remove-by-uid`?

@deftp {GOOPS method} flush! store
Write all pending transactions to the underlying store.
@end deftp

@subsection Reading Data

@deftp {GOOPS method} list-entries store
Retrieve all entries in the store, as a list of href, VCALENDAR
objects pairs. Further processing (such as expansion of recurrence
rules) MUST NOT be performed.
@end deftp

@deftp {GOOPS method} list-entries/shallow store
List all href's present in the store. For many stores, this could be
much faster than actually retrieving all entries.

A default implementation which dispatches to @code{list-entries} exists.
@end deftp

@c @deftp {GOOPS method} get-by-uid store uid
@c @end deftp

@deftp {GOOPS method} get-by-href store href
Retrive an entry by its href. Href should be assumed to only contain
the final component part, since the ``part'' part would be stripped by
the WebDAV server before we get here.
@end deftp

@c TODO return here once I figure out reports
@c @deftp {GOOPS method} caldav-filter store query
@c Runs the filter provided by the CALDAV:calendar-query REPORT
@c (RFC 4791 §7.8.)
@c @end deftp

@subsubsection Metadata

WebDAV and CalDAV specifies a number of properties which all calendar
collections may implement. To avoid re-writing the XML parsing step
for each data store, these methods are provided as simpler
implementations.

Each getter provides a default implementation which returns @code{#f},
indicating that the store has no value for that resource.

@c TODO link relevant WebDAV propreties elsewhere in the documentation
@c TODO and explain how these interact with the WebDAV property system.

@c TODO shouldn't set-*! and remove-*! have default implementations,
@c which throws `not-implemented`/`protected`?


@deftp  {GOOPS method} store-color store
@deftpx {GOOPS method} set-store-color! store color
@deftpx {GOOPS method} remove-store-color! store
Optional color of the data store (or rather, color of a calendar).

TODO each backend basically has weird requirements for what is
accepted. Each store MUST return either #f or a color object.
@c TODO link color
And during storage should convert the color object to the closest
match representable by its internal format.



This color, per RFC 7986, §5.9, should satisfy the rules for a CSS3
color, per §4.3 of W3C.REC-css3-color-20110607@footnote{
@example
Celik, T., Lilley, C., and D. Baron, "CSS Color Module
Level 3", World Wide Web Consortium Recommendation
REC-css3-color-20110607, June 2011,
<https://www.w3.org/TR/2011/REC-css3-color-20110607>.
@end example
}                               @c TODO proper references

Currently, no WebDAV property is registered for this data.
@c TODO webdav property?

@c ;; TODO check color specification for all known implementations:
@c ;; - vdir: `#\d{6}`
@c ;; - caldav: no color system defined
@c ;; - old apple calendar standard: I fail to find any form of documentation online, but it seems to be `#\d{6}`
@c ;; - new iCalendar standard: CSS3 color rules

@end deftp

@deftp  {GOOPS method} store-displayname store
@deftpx {GOOPS method} set-store-displayname! store name
@deftpx {GOOPS method} remove-store-displayname! store
Human readable name for the component.

Links to the WebDAV property DAV:displayname, and matches the NAME
property per RFC 7986.

@c TODO link DAV:displayname
@end deftp

@deftp  {GOOPS method} store-description store
@deftpx {GOOPS method} set-store-description! store description
@deftpx {GOOPS method} remove-store-displayname! store
Slightly longer description of what this calendar is about.

Links to the WebDAV property CalDAV:calendar-description, and matches
to the DESCRIPTION property per RFC 7986.

@c TODO link CalDAV:calendar-description
@end deftp

@deftp  {GOOPS method} store-calendar-timezone store
@deftpx {GOOPS method} set-store-description! store timezone
@deftpx {GOOPS method} remove-store-displayname! store
@c TODO write this
@c TODO link CalDAV:calendar-timezone
@c TODO content-type negotiation, but on the actual property
@end deftp

@c This menu appears before the other subsubsections in this document,
@c Which is exactly what we want
@include vcomponent/data-stores/file.texi
@include vcomponent/data-stores/vdir.texi
@include vcomponent/data-stores/sqlite.texi
@include vcomponent/data-stores/caldav.texi
