@node Data Formats
@section Data Formats

Data formats are the serialization formats for components.
The primary serialization format is iCalendar, but xCalendar and
sxCalendar also exists.

Each available format should be included as
@code{(vcomponent formats @var{format-name})}.
Which module corresponds to what file type is currently defined out of
band.

Each module should expose the following procedures.

@defun serialize component port
Write a serialized representation of @var{component} to @var{port}.
@end defun

@defun deserialize port
Read a serialized representation of a component from @var{port}, and
return the deserialized instance of this object.
@end defun

@subsection iCalendar
RFC 5545

@subsection xCal
