<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
xmlns="http://www.w3.org/1999/xhtml"
xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
xmlns:IC="urn:ietf:params:xml:ns:icalendar-2.0"
>

<!--
Quick proof-of-concept for formatting xcal documents into HTML.
-->

<xsl:template match="/">
 <html>
  <head>
   <meta charset="UTF-8"/>
   <title>Calendar File</title>
   <style>
    article {
      border: 1px solid black;
    }

    header {
     border-bottom: 1px solid black;
     font-size: 150%;
    }
   </style>
  </head>
  <body>
   <h1>Calendar File</h1>
   <p>Generated by <code><xsl:value-of select="//IC:vcalendar/IC:properties/IC:prodid" /></code></p>

   <xsl:for-each select="//IC:vevent">
    <article>
     <header><xsl:value-of select="IC:properties/IC:summary"/></header>
     <main>
      <xsl:value-of select="IC:properties/IC:description"/>
      <pre>
       UID: <xsl:value-of select="IC:properties/IC:uid" />
      </pre>
     </main>
    </article>
   </xsl:for-each>
  </body>
 </html>
</xsl:template>

</xsl:stylesheet>
