@node WebDAV Resource Tree Builder
@section Resource Tree Builder

@code{(calp webdav builder)}

@defun build-webdav-resource-tree resources
Creates a new WebDAV resource tree
suitable for passing to webdav-handler
with the given resources created and mounted under their respective places.

The @var{resources} argument is a list of resource declarations.

@itemize @bullet{}
@item
Absolute path to the resource.

@item
Resource type symbol.

This is lookup up as @code{(@ (calp webdav resource @var{type})
make-resource)}, which is then applied to the remaining arguments.

@item
Arguments to resource type constructor
@end itemize

@example
(build-webdav-resource-tree
  `(("/x" virtual
    content: ,my-content)))

;; would be equivalent to

(define root (make <virtual-resource> name: "root"))
(define node (make <virtual-resource>
                   name: "x"
                   content: my-content))
(mount-resource! root node)
root ; return value
@end example

@end defun
