@node WebDAV Properties
@section Properties

@itemize
@item @code{(calp webdav property)}
@item @code{(calp webdav propfind)}
@end itemize

@subsection Default Live Properties

@deftp {GOOPS method} creationdate
@end deftp

@deftp {GOOPS method} displayname
@end deftp

@deftp {GOOPS method} getcontentlanguage
@end deftp

@deftp {GOOPS method} getcontentlength
@end deftp

@deftp {GOOPS method} getcontenttype
@end deftp

@deftp {GOOPS method} getetag
@end deftp

@deftp {GOOPS method} getlastmodified
@end deftp

@deftp {GOOPS method} lockdiscovery
@end deftp

@deftp {GOOPS method} resourcetype
@end deftp

@deftp {GOOPS method} supportedlock
@end deftp
