@node WebDAV Properties
@section Properties

Each resource has a set of properties, which are additional data
besides the resources content. All properties are proper xml
fragments, and here implemented as namespaced sxml objects.

Properties are divided into @emph{live} and @emph{dead}
properties. @b{Dead} properties are stored as is, in an implementation
defined way depending on the resource type (for example, resources
backed by a filesystem may store them in extended file attributes, or
sidecar files). @b{Live} properties are managed by the server, and use
go through methods when being read or written to.

When setting property values, the resource is first checked if a live
property of that name exists, before defaulting to setting (and
possibly creating) a dead property. This ensures that no live property
isn't accidentally ``shadowed'' by a dead property.

When retrieving specific properties, dead properties are checked
first. This since dead property lookup is assumed to be effectively
instant, while live properties may incur costly computations. It in
theory also allows specific resource implementations to treat some
live properties as sneaky dead properties (for example,
DAV:displayname). This is however discouraged.

@include webdav/properties/access.texi
@include webdav/properties/implementing.texi
@include webdav/properties/objects.texi
@include webdav/properties/default-live.texi

