@node WebDAV Resource Types
@section Resource Types

Resource types provided ``out-of-the-box''. These all reside in the
@code{calp webdav resource} namespace, and export a procedure named
@code{make-resource}. This to allow for the builder (@ref{WebDAV
Resource Tree Builder}) to initialize resources from raw data, by
executing @code{(@@ (calp webdav resource ,type) make-resource)}.

Each page will document the expected use case for each resource, how
it extends common methods, and any extra properties or rules it
imposes for resources.

@include webdav/resource-types/calendar.texi
@include webdav/resource-types/file.texi
@include webdav/resource-types/virtual.texi
