@node WebDAV Resource Types
@section Resource Types

@subsection @code{(calp webdav resource base)}

Implementation of @code{(calp webdav resource)}. Exists to possibly
avoid dependency loops.

@subsection @code{(calp webdav resource calendar)}
@subsection @code{(calp webdav resource file)}

Resources backed by the file system.

@defun file-resource? x
@end defun

@deftp {GOOPS method} children <file-resource>
@end deftp

@deftp {GOOPS method} is-collection? <file-resource>
@end deftp

@deftp {GOOPS method} creationdate <file-resource>
Retrived directly from the file through @command{stat -c %W $@{filename@}}.
@end deftp

@deftp {GOOPS method} content <file-resource>
@deftpx {GOOPS method} set-content! <file-resource> data
Directly interfaced with the file.

Data can't be retrieved for collections, and will always be
returned as a bytevector for non-collections.

Data can be set either as a string or a bytevector. When a string is
used Guile's current encoding will be used.
@end deftp

@subsection @code{(calp webdav resource virtual)}
