@node Timespec
@section Timespec

Timespecs are two datatypes mushed together (as per usual in this
library). They firstly represents signed time values, solving the
problem that time objects can't be negative. They also encode which
``type'' of time an object refers to. This is borrowed from the
zoneinfo compiler, and may be one of

@itemize @bullet
@item standard
For local times without a daylights savings shift.
@item daylight
For local times, with a daylights savings shift.
@item wall
Which is the time your wall clock shows.
@item utc
For times in UTC.
@end itemize

For example, the EU timezone rules dictate that daylights savings time
ends the last sunday of october, at 01:00 UTC. In effect, this means
that in Sweden (which goes between an offset of +1 and +2) moves their
clocks back at 03:00 local time. This means that we first have the
time 02:30 (summer) followed by 02:30 (standard), and that ``all''
Europeans change their clocks at the same instant.

In contrast, the USA says that daylights savings time ends at 02:00
wall time, meaning that when your local clock shows 02:00, you move it
back to 01:00.

@b{TODO} standard/daylight indicators needs to be added to datetime
objects. Currently, there is no way to differentiate between the
``overlapping'' times.

@defun timespec time [sign='+] [type]

    @defun timespec? x
    @end defun

    @defun timspec-time timespec
    Should be a time object.
    @end defun

    @defun timspec-sign timespec
    @code{'+} or @code{'-}
    @end defun

    @defun timspec-type timespec
    One of @code{#f}, @code{standard}, @code{daylight}, @code{wall},
    or @code{utc}.
    @end defun

@end defun

@defun timespec+ timespecs ...
Add a series of timespecs, which must all be of the same type
(technically not, an the only ``issue'' is that a warning will be
signaled, but it's nonsence to add timespecs of differing types).

@example
(timespec+ (timespec #01:00:00 '+ 'wall)
           (timespec #01:00:00 '+ 'wall))
⇒ (timespec #02:00:00 '+ 'wall)

(timespec+ (timespec #01:00:00 '+ 'wall)
           (timespec #01:40:00 '- 'wall))
⇒ (timespec #00:40:00 '- 'wall)

(timespec+ (timespec #01:00:00 '+ 'wall)
           (timespec (time hour: 300) '+ 'wall))
⇒ (timespec (time hour: 301) '+ 'wall)
@end example
@end defun

@defun parse-time-spec string
Parses a time as pxpected, with optional minute, seconds, and
millisecond components (milliseconds are currently discarded),
alongside an optional ± prefix and an optional suffix, being one of
the following letters
@itemize @bullet
@item s = standard
@item d = daylight
@item w = wall
@item u, g, z = utc
@end itemize
@end defun
