@node Color
@section Color

@defvar STR-RESET
ANSI escape sequence for removing all current formatting, as a string.
@end defvar

@defun color-escape n
Generates an RGB color escape code. @var{n} can either be @code{#f},
in which case the empty string is returned, or a a 24 bit color code
encoded hexadecimaly as @samp{#RRGGBB}.
@end defun
