@node HTTP Routes
@section (web http make-routes)

@defun parse-endpoint-string str
Parses a string specifying an endpoint as per @code{make-route}.

Returns two values: a reogexp like string matching the path component
of an uri, and the list of symbols referenced in the source pattern.
@end defun

@defun make-handler
Creates a new handler context object, which can be turned into a
``true'' request handler through @code{realize-handler}.o
@end defun

@defun (realize-handler handler) request body state
@code{realize-handler} returns a procedure taking a request, body, and
state variable, and returns the same. Suitable to use as a handler in
@xref{Web Server,run-server,run-server,guile}.
@end defun

@defun set-request-start-log! handler callback
@defunx set-request-end-log! handler callback
@defunx set-request-404-handler! handler callback
Sets various callbacks for parts of the request handling.

Each procedure is called with the keyword arguments, with the same
semantics as their equivalents in @code{make-route}
@itemize @bullet{}
@item request
@item request-body
@item method
@item uri
@item version
@item headers
@item meta
@item scheme
@item userinfo
@item host
@item port
@item path
@item query
@end itemize

@code{start-log} is called after the incomming request is parsed, but
before a handler is picked and run. It defaults to a no-op procedure.

@code{end-log} is ran after a handler is run, and a value exist.
It also gets passed the keyword arguments @code{response-headers} and
@code{response-body}. It defaluts to a no-op procedure.

@code{404-handler} is called when no registered endpoint matches the
request. It @emph{should} return a response object with a 404 status
code, and defaults to a super simple ``not found'' page.

@end defun


@defun add-route! handler route
@end defun

@defmac make-route (method path parameter body ...)
Creates an object suitable to pass as a route to @code{add-route!}.

@example
(make-route
  (GET "/path/:a" (a b)
    (return '((content-type text/plain))
            (format #f "a=~a, b=~a" a b))))
@end example

The paths can contain embedded variables, which start with
colon, and their name continues until the next slash or period (or end
of string). Each path-embedded parameter must be present in the
parameter list.

The parameter list must contain all path-embedded parameters, and can
contain any other parameters, which will be bound from the query
parameters, or stay @code{#f} if not supplied by the browser.

The body should return one to three values, either directly, or
through an early return by calling the procedure @code{return}.

@defun return headers [body] [new-state]
@end defun

Inside the body, the following variables are bound to enable producing
the body:

@defvar request
@defvarx body
The raw request headers and request body.
@end defvar

@defvar state
The optional state.
@end defvar

@defvar r:method
@defvarx r:uri
@defvarx r:version
@defvarx r:headers
@defvarx r:meta
The requests components
@end defvar

@defvar r:scheme
@defvarx r:userinfo
@defvarx r:host
@defvarx r:port
@defvarx r:path
@defvarx r:query
@defvarx r:fragment
The request uri's components.
@end defvar

@end defmac
