@node Generally Useful Utilities
@chapter Generally Useful Utilities

@include guile/datetime.texi
@include guile/zic.texi
@include guile/srfi-41.texi
@include guile/util.texi
@include guile/util-path.texi
@include guile/util-config.texi
@include guile/util-exceptions.texi
@include guile/base64.texi
@include guile/xdg-basedir.texi
@include guile/glob.texi
@include guile/graphviz.texi
@include guile/crypto.texi
