@node Generally Useful Utilities
@chapter Generally Useful Utilities

These are all general utilitios with no direct relation to Calp. Many
of these should be generally useful in any project.

@include general/datetime.texi
@include general/zic.texi
@include general/srfi-41.texi
@include general/util.texi
@include general/uuid.texi
@include general/io.texi
@include general/bst.texi
@include general/util-path.texi
@include general/util-config.texi
@include general/util-exceptions.texi
@include general/base64.texi
@include general/xdg-basedir.texi
@include general/glob.texi
@include general/graphviz.texi
@include general/crypto.texi
@include general/graph.texi
@include general/options.texi
