@node VComponents
@chapter VComponents

Procedures for manipulating VComponents.
VComponents are the general container type as specified by RFC5545
(iCalendar). The term VComponent isn't from the standard, but rather
the generialization of VCALENDAR, VEVENT, ...

Some of these values are still Calp specific.

@include vcomponent/introduction.texi
@include vcomponent/general.texi
@include vcomponent/group.texi
@include vcomponent/create.texi

@include vcomponent/data-formats.texi
@include vcomponent/data-stores.texi
