@node WebDAV
@chapter WebDAV
@cindex webdav

This is an implementation of RFC 4918 (WebDAV).
At its core is the server handler @code{webdav-handler}, which
maps HTTP requests onto methods in the resource tree. Resource tree
operations are implemented by a series of GOOPS method, declared in
the module @code{(calp webdav resource)}, and implemented in varying
ways depending on the source of the resource.

In general, resource implementations only handle immediate children
(and parents), and leaves deep lookup, deletions, and similar to the
wrapping code.

@include webdav/server.texi
@include webdav/http-error.texi
@include webdav/resource.texi
@include webdav/properties.texi
@include webdav/resource-types.texi
@include webdav/util.texi
@include webdav/builder.texi
