@node WebDAV Resource Data
@subsection Resource Data

These methods provide general data about the resource, and are used as
the basis for their corresponding properties, and for HTTP GET requests.
Each method may return @code{#f} if no suitable value can be given for
the resource, in which case the property will be omitted from both GET
and PROPFIND requests. For general information about accessing
properties, see @ref{Accessing Properties}.

Unless otherwise noted, the default implementation for all of these
simply returns @code{#f}.

@deftp {GOOPS method} creation-date resource
Must return a @code{datetime} object.
@end deftp

@deftp {GOOPS method} content-language resource
Should return a string containing a language tag, as defined in §8.5.1
in RFC 9110 (HTTP Semantics).
@end deftp

@deftp {GOOPS method} content-length resource
An exact integer specifying the byte length of the content.

If the resource has content, and the content returned is a bytevector,
then the default implementation returns the result of
@code{bytevector-length}, or @code{#f} otherwise.
@end deftp

@deftp {GOOPS method} content-type resource
Should return a string containing a media type according to §8.3.1 of
RFC 9110. For example @code{application/octet-stream}.
@end deftp

@deftp {GOOPS method} display-name resource
Retrieve a human readable name of the resource.
@end deftp

@deftp {GOOPS method} etag resource
Return the etag for the content of this resource. If a string is
returned, then it @emph{must} contain a valid etag, including
quotation marks.

@c Wouldn't etag objects be a good idea?
@c (define-type (etag) (tag type: string?) (weak? type: boolean? default: #f)
@c (define (etag->string et) (format #f "~a\"~a\"" (if (weak? et) @c "W/" "") (tag et)))
@end deftp

@deftp {GOOPS method} last-modified resource
Must return a @code{datetime} object.
@end deftp
