@node Period iCalendar Type
@subsubsection Period iCalendar Type

@c TODO document that the TZID property MUST be hanled as for
@c DATE-TIME values.

@defun period [#:start] [#:end]
@end defun

@defun period-start p [start]
@defunx period-end p [end]
@end defun

@deftp {Lens} period-start*
@deftpx {Lens} period-end*
@end deftp

@defun period->utc-datetimes
TODO
@end defun
