#!/bin/bash

here=$(dirname "$(realpath "$0")")
cd "$here" || {
	echo "Failed to cd to location of script ($here)"
	exit 1
}

export PATH="$here/node_modules/.bin:$PATH"

if [ -n "$TMUX" ]; then
	tmux new-window "scss --watch -I. style.scss:style.css"
	tmux new-window "tsc --watch"
else
	tmux \
		 new-session "scss --watch -I. scss/style.scss:out/style.css" \; \
		 split-window "tsc --watch --noEmit" \; \
		 split-window "make watch-esbuild" \; \
		 rename-session "calp watch" \; \
		 select-layout even-vertical

 fi
