#!/bin/bash
if [ $# -eq 0 ]; then
	echo "Usage: $0 version" > /dev/stderr
	exit 1
fi

VERSION=$1
sed -i "s/^pkgver=.*/pkgver=$VERSION/" system/PKGBUILD
sed -i "s/^(define-public version.*/(define-public version \"$VERSION\")/" module/calp.scm
