(define-module (test text-numbers-sv)
  :use-module (srfi srfi-1)
  :use-module (srfi srfi-64)
  :use-module (srfi srfi-71)
  :use-module (srfi srfi-88)
  :use-module (text numbers))

;;; Readable integer "literals", until srfi-169 gets ported to Guile
(define (n s)
  (fold (lambda (x p) (+ x (* 1000 p)))
        0 (map string->number (string-split s #\_))))

(test-group "Cardinal numbers"

  (test-equal "minus två"                     (number->string-cardinal -2 language: 'sv))
  (test-equal "minus ett"                     (number->string-cardinal -1 language: 'sv))
  (test-equal "noll"                          (number->string-cardinal 0  language: 'sv))
  (test-equal "ett"                           (number->string-cardinal 1  language: 'sv))
  (test-equal "två"                           (number->string-cardinal 2  language: 'sv))
  (test-equal "tre"                           (number->string-cardinal 3  language: 'sv))
  (test-equal "fyra"                          (number->string-cardinal 4  language: 'sv))
  (test-equal "fem"                           (number->string-cardinal 5  language: 'sv))
  (test-equal "sex"                           (number->string-cardinal 6  language: 'sv))
  (test-equal "sju"                           (number->string-cardinal 7  language: 'sv))
  (test-equal "åtta"                          (number->string-cardinal 8  language: 'sv))
  (test-equal "nio"                           (number->string-cardinal 9  language: 'sv))
  (test-equal "tio"                           (number->string-cardinal 10 language: 'sv))
  (test-equal "elva"                          (number->string-cardinal 11 language: 'sv))
  (test-equal "tolv"                          (number->string-cardinal 12 language: 'sv))
  (test-equal "tretton"                       (number->string-cardinal 13 language: 'sv))
  (test-equal "fjorton"                       (number->string-cardinal 14 language: 'sv))
  (test-equal "femton"                        (number->string-cardinal 15 language: 'sv))
  (test-equal "sexton"                        (number->string-cardinal 16 language: 'sv))
  (test-equal "sjutton"                       (number->string-cardinal 17 language: 'sv))
  (test-equal "arton"                         (number->string-cardinal 18 language: 'sv))
  (test-equal "nitton"                        (number->string-cardinal 19 language: 'sv))
  (test-equal "tjugo"                         (number->string-cardinal 20 language: 'sv))
  (test-equal "tjugoett"                      (number->string-cardinal 21 language: 'sv))
  (test-equal "trettio"                       (number->string-cardinal 30 language: 'sv))
  (test-equal "trettiotvå"                    (number->string-cardinal 32 language: 'sv))
  (test-equal "fyrtio"                        (number->string-cardinal 40 language: 'sv))
  (test-equal "fyrtiotre"                     (number->string-cardinal 43 language: 'sv))
  (test-equal "femtio"                        (number->string-cardinal 50 language: 'sv))
  (test-equal "femtiofyra"                    (number->string-cardinal 54 language: 'sv))
  (test-equal "sextio"                        (number->string-cardinal 60 language: 'sv))
  (test-equal "sextiofem"                     (number->string-cardinal 65 language: 'sv))
  (test-equal "sjuttio"                       (number->string-cardinal 70 language: 'sv))
  (test-equal "sjuttiosex"                    (number->string-cardinal 76 language: 'sv))
  (test-equal "åttio"                         (number->string-cardinal 80 language: 'sv))
  (test-equal "åttiosju"                      (number->string-cardinal 87 language: 'sv))
  (test-equal "nittio"                        (number->string-cardinal 90 language: 'sv))
  (test-equal "nittioåtta"                    (number->string-cardinal 98 language: 'sv))
  (test-equal "etthundra"                     (number->string-cardinal 100 language: 'sv))
  (test-equal "etthundraett"                  (number->string-cardinal 101 language: 'sv))
  (test-equal "etthundraåttioåtta"            (number->string-cardinal 188 language: 'sv))
  (test-equal "tvåhundra"                     (number->string-cardinal 200 language: 'sv))
  (test-equal "tvåhundrasextioett"            (number->string-cardinal 261 language: 'sv))
  (test-equal "ettusen"                       (number->string-cardinal 1000 language: 'sv))
  (test-equal "ettusen sex"                   (number->string-cardinal 1006 language: 'sv))
  (test-equal "ettusen niohundrasjuttiosju"   (number->string-cardinal 1977 language: 'sv))
  (test-equal "tvåtusen fyrtioåtta"           (number->string-cardinal 2048 language: 'sv))

  (test-equal "tiotusen"     (number->string-cardinal 10000 language: 'sv))
  (test-equal "nittiotusen"  (number->string-cardinal 90000 language: 'sv))
  (test-equal "nittioåttatusen sjuhundrasextiofem" (number->string-cardinal 98765 language: 'sv))

  (test-equal "etthundratusen"  (number->string-cardinal 100000 language: 'sv))
  (test-equal "niohundratusen"  (number->string-cardinal 900000 language: 'sv))
  (test-equal "niohundraåttiosjutusen sexhundrafemtiofyra" (number->string-cardinal 987654 language: 'sv))

  (test-equal "en miljon"     (number->string-cardinal 1000000 language: 'sv))
  (test-equal "nio miljoner"  (number->string-cardinal 9000000 language: 'sv))
  (test-equal "nio miljoner åttahundrasjuttiosex tusen femhundrafyrtiotre"
    (number->string-cardinal 9876543 language: 'sv))

  (test-equal "tio miljoner"       (number->string-cardinal 10000000  language: 'sv))
  (test-equal "etthundra miljoner" (number->string-cardinal 100000000 language: 'sv))
  (test-equal "niohundraåttiosju miljoner sexhundrafemtiofyra tusen trehundratjugoett"
    (number->string-cardinal 987654321 language: 'sv))
  (test-equal "en miljard"         (number->string-cardinal (n "1_000_000_000")     language: 'sv))
  (test-equal "en biljon"          (number->string-cardinal (n "1_000_000_000_000") language: 'sv))
  (test-equal "en biljard"         (number->string-cardinal #e1e15  language: 'sv))
  (test-equal "tio biljarder"      (number->string-cardinal #e1e16  language: 'sv))
  (test-equal "etthundra biljarder" (number->string-cardinal #e1e17 language: 'sv))
  (test-equal "en biljard"         (number->string-cardinal (n "1_000_000_000_000_000") language: 'sv))
  (test-equal "en triljon"         (number->string-cardinal #e1e18 language: 'sv))
  (test-equal "en triljard"        (number->string-cardinal #e1e21 language: 'sv))
  (test-equal "en kvadriljon"      (number->string-cardinal #e1e24 language: 'sv))
  (test-equal "en kvadriljard"     (number->string-cardinal #e1e27 language: 'sv))
  (test-equal "en kvintiljon"      (number->string-cardinal #e1e30 language: 'sv))
  (test-equal "en kvintiljard"     (number->string-cardinal #e1e33 language: 'sv))
  (test-equal "en sextiljon"       (number->string-cardinal #e1e36 language: 'sv))
  (test-equal "en sextiljard"      (number->string-cardinal #e1e39 language: 'sv))
  (test-equal "en septiljon"       (number->string-cardinal #e1e42 language: 'sv))
  (test-equal "en septiljard"      (number->string-cardinal #e1e45 language: 'sv))
  (test-equal "en oktiljon"        (number->string-cardinal #e1e48 language: 'sv))
  (test-equal "en oktiljard"       (number->string-cardinal #e1e51 language: 'sv))
  (test-equal "en noniljon"        (number->string-cardinal #e1e54 language: 'sv))
  (test-equal "en noniljard"       (number->string-cardinal #e1e57 language: 'sv))
  (test-equal "en deciljon"        (number->string-cardinal #e1e60 language: 'sv))
  (test-equal "en deciljard"       (number->string-cardinal #e1e63 language: 'sv))
  (test-equal "det stora talet 10⁶⁶"
    (number->string-cardinal #e1e66 language: 'sv)))

(test-group "Ordinal numbers"
  (test-equal "nollte"                   (number->string-ordinal 0  language: 'sv a-form?: #t))
  (test-equal "första"                   (number->string-ordinal 1  language: 'sv a-form?: #t))
  (test-equal "andra"                    (number->string-ordinal 2  language: 'sv a-form?: #t))
  (test-equal "tredje"                   (number->string-ordinal 3  language: 'sv a-form?: #t))
  (test-equal "fjärde"                   (number->string-ordinal 4  language: 'sv a-form?: #t))
  (test-equal "femte"                    (number->string-ordinal 5  language: 'sv a-form?: #t))
  (test-equal "sjätte"                   (number->string-ordinal 6  language: 'sv a-form?: #t))
  (test-equal "sjunde"                   (number->string-ordinal 7  language: 'sv a-form?: #t))
  (test-equal "åttonde"                  (number->string-ordinal 8  language: 'sv a-form?: #t))
  (test-equal "nionde"                   (number->string-ordinal 9  language: 'sv a-form?: #t))
  (test-equal "tionde"                   (number->string-ordinal 10 language: 'sv a-form?: #t))
  (test-equal "elfte"                    (number->string-ordinal 11 language: 'sv a-form?: #t))
  (test-equal "tolfte"                   (number->string-ordinal 12 language: 'sv a-form?: #t))
  (test-equal "trettonde"                (number->string-ordinal 13 language: 'sv a-form?: #t))
  (test-equal "fjortonde"                (number->string-ordinal 14 language: 'sv a-form?: #t))
  (test-equal "femtonde"                 (number->string-ordinal 15 language: 'sv a-form?: #t))
  (test-equal "sextonde"                 (number->string-ordinal 16 language: 'sv a-form?: #t))
  (test-equal "sjuttonde"                (number->string-ordinal 17 language: 'sv a-form?: #t))
  (test-equal "artonde"                  (number->string-ordinal 18 language: 'sv a-form?: #t))
  (test-equal "nittonde"                 (number->string-ordinal 19 language: 'sv a-form?: #t))
  (test-equal "tjugonde"                 (number->string-ordinal 20 language: 'sv a-form?: #t))
  (test-equal "tjugoförsta"              (number->string-ordinal 21 language: 'sv a-form?: #t))
  (test-equal "tjugoandra"               (number->string-ordinal 22 language: 'sv a-form?: #t))
  (test-equal "tjugotredje"              (number->string-ordinal 23 language: 'sv a-form?: #t))
  (test-equal "trettiotredje"            (number->string-ordinal 33 language: 'sv a-form?: #t))
  (test-equal "fyrtiofjärde"             (number->string-ordinal 44 language: 'sv a-form?: #t))
  (test-equal "femtiofemte"              (number->string-ordinal 55 language: 'sv a-form?: #t))
  (test-equal "sextiosjätte"             (number->string-ordinal 66 language: 'sv a-form?: #t))
  (test-equal "sjuttiosjunde"            (number->string-ordinal 77 language: 'sv a-form?: #t))
  (test-equal "åttioåttonde"             (number->string-ordinal 88 language: 'sv a-form?: #t))
  (test-equal "nittionionde"             (number->string-ordinal 99 language: 'sv a-form?: #t))
  (test-equal "etthundrade"              (number->string-ordinal 100 language: 'sv a-form?: #t))
  (test-equal "tvåhundrade"              (number->string-ordinal 200 language: 'sv a-form?: #t))
  (test-equal "etthundratrettiofjärde"   (number->string-ordinal 134 language: 'sv a-form?: #t))
  (test-equal "sjuhundratrettiosjätte"   (number->string-ordinal 736 language: 'sv a-form?: #t))
  (test-equal "etttusende"                       (number->string-ordinal 1000 language: 'sv a-form?: #t))
  (test-equal "ettusen sjätte"                   (number->string-ordinal 1006 language: 'sv a-form?: #t))
  (test-equal "ettusen etthundrade"              (number->string-ordinal 1100 language: 'sv a-form?: #t))
  (test-equal "ettusen niohundratjugoandra"      (number->string-ordinal 1922 language: 'sv a-form?: #t))
  (test-equal "ettusen niohundranittionionde"    (number->string-ordinal 1999 language: 'sv a-form?: #t))
  (test-equal "tvåtusende"                       (number->string-ordinal 2000 language: 'sv a-form?: #t))
  (test-equal "tvåtusen första"                  (number->string-ordinal 2001 language: 'sv a-form?: #t))
  (test-equal "tretusende"                       (number->string-ordinal 3000 language: 'sv a-form?: #t))
  (test-equal "fyratusende"                      (number->string-ordinal 4000 language: 'sv a-form?: #t))
  (test-equal "femtusende"                       (number->string-ordinal 5000 language: 'sv a-form?: #t))
  (test-equal "sextusende"                       (number->string-ordinal 6000 language: 'sv a-form?: #t))
  (test-equal "sjutusende"                       (number->string-ordinal 7000 language: 'sv a-form?: #t))
  (test-equal "åttatusende"                      (number->string-ordinal 8000 language: 'sv a-form?: #t))
  (test-equal "niotusende"                       (number->string-ordinal 9000 language: 'sv a-form?: #t))
  (test-equal "niotusen åttahundrasjuttiosjätte" (number->string-ordinal 9876 language: 'sv a-form?: #t))

  (test-equal "tiotusende"     (number->string-ordinal 10000 language: 'sv a-form?: #t))
  (test-equal "tjugotusende"   (number->string-ordinal 20000 language: 'sv a-form?: #t))
  (test-equal "trettiotusende" (number->string-ordinal 30000 language: 'sv a-form?: #t))
  (test-equal "fyrtiotusende"  (number->string-ordinal 40000 language: 'sv a-form?: #t))
  (test-equal "femtiotusende"  (number->string-ordinal 50000 language: 'sv a-form?: #t))
  (test-equal "sextiotusende"  (number->string-ordinal 60000 language: 'sv a-form?: #t))
  (test-equal "sjuttiotusende" (number->string-ordinal 70000 language: 'sv a-form?: #t))
  (test-equal "åttiotusende"   (number->string-ordinal 80000 language: 'sv a-form?: #t))
  (test-equal "nittiotusende"  (number->string-ordinal 90000 language: 'sv a-form?: #t))
  (test-equal "nittioåttatusen sjuhundrasextiofemte"
    (number->string-ordinal 98765 language: 'sv a-form?: #t))

  (test-equal "etthundratusende"  (number->string-ordinal 100000 language: 'sv a-form?: #t))
  (test-equal "tvåhundratusende"  (number->string-ordinal 200000 language: 'sv a-form?: #t))
  (test-equal "trehundratusende"  (number->string-ordinal 300000 language: 'sv a-form?: #t))
  (test-equal "fyrahundratusende" (number->string-ordinal 400000 language: 'sv a-form?: #t))
  (test-equal "femhundratusende"  (number->string-ordinal 500000 language: 'sv a-form?: #t))
  (test-equal "sexhundratusende"  (number->string-ordinal 600000 language: 'sv a-form?: #t))
  (test-equal "sjuhundratusende"  (number->string-ordinal 700000 language: 'sv a-form?: #t))
  (test-equal "åttahundratusende" (number->string-ordinal 800000 language: 'sv a-form?: #t))
  (test-equal "niohundratusende"  (number->string-ordinal 900000 language: 'sv a-form?: #t))
  (test-equal "niohundraåttiosjutusen sexhundrafemtiofjärde"
    (number->string-ordinal 987654 language: 'sv a-form?: #t))

  (test-equal "miljonte"      (number->string-ordinal 1000000 language: 'sv a-form?: #t))
  (test-equal "två miljonte"  (number->string-ordinal 2000000 language: 'sv a-form?: #t))
  (test-equal "tre miljonte"  (number->string-ordinal 3000000 language: 'sv a-form?: #t))
  (test-equal "fyra miljonte" (number->string-ordinal 4000000 language: 'sv a-form?: #t))
  (test-equal "fem miljonte"  (number->string-ordinal 5000000 language: 'sv a-form?: #t))
  (test-equal "sex miljonte"  (number->string-ordinal 6000000 language: 'sv a-form?: #t))
  (test-equal "sju miljonte"  (number->string-ordinal 7000000 language: 'sv a-form?: #t))
  (test-equal "åtta miljonte" (number->string-ordinal 8000000 language: 'sv a-form?: #t))
  (test-equal "nio miljonte"  (number->string-ordinal 9000000 language: 'sv a-form?: #t))
  (test-equal "nio miljoner åttahundrasjuttiosex tusen femhundrafyrtiotredje"
    (number->string-ordinal 9876543 language: 'sv a-form?: #t))

  (test-equal "tio miljonte"       (number->string-ordinal 10000000  language: 'sv a-form?: #t))
  (test-equal "etthundra miljonte" (number->string-ordinal 100000000 language: 'sv a-form?: #t))
  (test-equal "niohundraåttiosju miljoner sexhundrafemtiofyra tusen trehundratjugoförsta"
    (number->string-ordinal 987654321 language: 'sv a-form?: #t))
  (test-equal "miljarde"           (number->string-ordinal 1000000000    language: 'sv a-form?: #t))
  (test-equal "biljonte"           (number->string-ordinal 1000000000000 language: 'sv a-form?: #t))
  (test-equal "niohundranittionio biljoner niohundranittionio miljarder niohundranittionio miljoner niohundranittionio tusen niohundranittionionde"
    (number->string-ordinal (1- #e1e15) language: 'sv))
  (test-equal "biljarde" (number->string-ordinal #e1e15 language: 'sv))
  (test-equal "10⁶⁶:e"
    (number->string-ordinal #e1e66 language: 'sv))
 )

(test-group "each-string sv"
  (test-equal "varje"
    (each-string 1 language: 'sv))
  (test-equal "varannan"
    (each-string 2 language: 'sv))
  (test-equal "vartannat"
    (each-string 2 language: 'sv neutrum: #t))
  (test-equal "var tredje"
    (each-string 3 language: 'sv))
  (test-equal "vart tredje"
    (each-string 3 language: 'sv neutrum: #t)))

'((text numbers)
  (text numbers sv))
