#!/bin/bash

dir=$(mktemp -d)
here=$(dirname $(realpath $0))

guild use2dot -m '(calp main)' -- `find module -name \*.scm` > $dir/use.dot
$here/change_graph.py $dir/use.dot $dir/use2.dot
grep -v '\(srfi\|ice-9\|(util)\)' $dir/use2.dot > $dir/use3.dot

fdp $dir/use3.dot -Tpdf -o use.pdf
