;;; Commentary:
;;; This is an autogenerated file
;;; Generated from "tzdata-latest.tar.gz"
;;; With sha256 checksum:
;;; 4aa79e4effee53fc4029ffe5f6ebe97937282ebcdf386d5d2da91ce84142f957
;;; Limited to the explicitly mentioned zones:
;;; - UTC
;;; Code:

(define-module
 (datetime timezone vendored-tzdb)
 #:use-module
 ((datetime core) #:select (datetime date time))
 #:use-module
 ((datetime timespec) #:select (timespec))
 #:use-module
 ((datetime zoneinfo)
  #:select
  (parsed-zic-intermediary intermediary->zoneinfo zone-entry zi-rule zone-link))
 #:export
 (zoneinfo-intermediary zoneinfo-database))

(with-output-to-port
 (current-error-port)
 (lambda ()
   (display "************************************************************\n")
   (display "WARNING! (datetime) is compiled with only a very basic\n")
   (display "timezone database. Generate a new one by running:\n")
   (display "calp update-zoneinfo \\\n")
   (display "    -o $LOAD_PATH/datetime/timezone/vendored-tzdb.scm \\\n")
   (display "    [limeted zone set (defaults to all zones)]\n")
   (display "************************************************************\n")))

(define zoneinfo-intermediary
  (parsed-zic-intermediary
   #:rules
   (list)
   #:zones
   (list (list "Etc/UTC"
               (zone-entry
                #:stdoff
                (timespec #00:00:00)
                #:rule
                (timespec #00:00:00 '+ 'standard)
                #:format
                "UTC"
                #:until
                #f)))
   #:links
   (list (zone-link #:name "UTC" #:target "Etc/UTC"))))

(define zoneinfo-database (intermediary->zoneinfo zoneinfo-intermediary))
