;;; Commentary:
;;; This is an autogenerated file
;;; Generated from "tzdata-latest.tar.gz"
;;; With sha256 checksum:
;;; 4aa79e4effee53fc4029ffe5f6ebe97937282ebcdf386d5d2da91ce84142f957
;;; Limited to the explicitly mentioned zones:
;;; - Europe/Stockholm
;;; - UTC
;;; - America/New_York
;;; Code:

(define-module
 (datetime timezone vendored-tzdb)
 #:use-module
 ((datetime core) #:select (datetime date time))
 #:use-module
 ((datetime zoneinfo)
  #:select
  (parsed-zic-intermediary intermediary->zoneinfo zone-entry zi-rule zone-link))
 #:export
 (zoneinfo-intermediary zoneinfo-database))

(define zoneinfo-intermediary
  (parsed-zic-intermediary
   #:rules (list)
   #:zones (list)
   #:links (list)))
(define zoneinfo-database (intermediary->zoneinfo zoneinfo-intermediary))
